import { Job, JobStatus, InvoiceStatus, Employee, JournalEntry, Customer } from './types';

export const PAPER_TYPES = [
  'コート紙 90kg',
  'マットコート紙 110kg',
  '上質紙 70kg',
  'アートポスト 180kg',
  'ミラーコート・プラチナ 220kg',
  'サテン金藤 135kg'
];

export const FINISHING_OPTIONS = [
  'なし',
  'PP加工（グロス）',
  'PP加工（マット）',
  '箔押し',
  'エンボス加工',
  '型抜き'
];

// 経営の意思決定に必要な固定費を定義
export const FIXED_COSTS = {
  monthly: {
    labor: 1200000, // 人件費 (L)
    other: 800000,   // その他経費 (G) - 家賃、光熱費、減価償却など
  }
};

// --- Mock Data for Demo Mode ---
export const MOCK_JOBS: Job[] = [
  {
    id: 'demo_001',
    clientName: 'カフェ・ソレイユ',
    title: '春のキャンペーンA5チラシ',
    status: JobStatus.Completed,
    dueDate: '2024-04-15',
    quantity: 2000,
    paperType: 'マットコート紙 110kg',
    finishing: 'なし',
    details: '両面カラー印刷。デザインデータは支給。',
    createdAt: new Date('2024-04-01T10:00:00Z'),
    price: 95000,
    variableCost: 42000,
    invoiceStatus: InvoiceStatus.Paid,
  },
  {
    id: 'demo_002',
    clientName: '株式会社TechNext',
    title: '新製品発表会パンフレット',
    status: JobStatus.InProgress,
    dueDate: '2024-05-20',
    quantity: 500,
    paperType: 'アートポスト 180kg',
    finishing: 'PP加工（マット）',
    details: 'A4サイズ、8ページ中綴じ冊子。',
    createdAt: new Date('2024-04-25T14:30:00Z'),
    price: 180000,
    variableCost: 85000,
    invoiceStatus: InvoiceStatus.Invoiced,
  },
  {
    id: 'demo_003',
    clientName: 'デザインスタジオ・イロドリ',
    title: '名刺（箔押し加工）',
    status: JobStatus.Pending,
    dueDate: '2024-06-01',
    quantity: 300,
    paperType: 'ミラーコート・プラチナ 220kg',
    finishing: '箔押し',
    details: 'ロゴ部分に金の箔押し。',
    createdAt: new Date('2024-05-10T11:00:00Z'),
    price: 45000,
    variableCost: 20000,
    invoiceStatus: InvoiceStatus.Uninvoiced,
  },
   {
    id: 'demo_004',
    clientName: 'カフェ・ソレイユ',
    title: '夏のクーポン券',
    status: JobStatus.Completed,
    dueDate: '2024-06-10',
    quantity: 3000,
    paperType: '上質紙 70kg',
    finishing: '型抜き',
    details: 'ミシン目加工あり。',
    createdAt: new Date('2024-05-15T09:00:00Z'),
    price: 78000,
    variableCost: 35000,
    invoiceStatus: InvoiceStatus.Paid,
  },
];

export const MOCK_JOURNAL_ENTRIES: JournalEntry[] = [
    { id: 'demo_j_001', date: new Date('2024-04-30T00:00:00Z'), account: '現金', debit: 95000, credit: 0, description: '売上入金 カフェ・ソレイユ (demo_001)' },
    { id: 'demo_j_002', date: new Date('2024-04-30T00:00:00Z'), account: '売掛金', debit: 0, credit: 95000, description: '売上入金 カフェ・ソレイユ (demo_001)' },
    { id: 'demo_j_003', date: new Date('2024-05-01T00:00:00Z'), account: '消耗品費', debit: 150000, credit: 0, description: '印刷用紙の購入 (ABC製紙)' },
    { id: 'demo_j_004', date: new Date('2024-05-01T00:00:00Z'), account: '現金', debit: 0, credit: 150000, description: '印刷用紙の購入 (ABC製紙)' },
    { id: 'demo_j_005', date: new Date('2024-05-25T00:00:00Z'), account: '地代家賃', debit: 300000, credit: 0, description: '5月分家賃' },
    { id: 'demo_j_006', date: new Date('2024-05-25T00:00:00Z'), account: '現金', debit: 0, credit: 300000, description: '5月分家賃' },
];

const createMockCustomer = (customerData: Partial<Customer>): Customer => ({
    id: '',
    customerCode: null,
    customerCodeAlt: null,
    customerName: '',
    customerNameKana: null,
    name2: null,
    customerRank: null,
    customerDivision: null,
    salesType: null,
    supportCompanyFlag: null,
    zipCode: null,
    address1: null,
    address2: null,
    address3: null,
    nearestStation: null,
    phoneNumber: null,
    fax: null,
    representative: null,
    foundationDate: null,
    capital: null,
    annualSales: null,
    employeesCount: null,
    creditLimit: null,
    closingDay: null,
    payDay: null,
    recoveryMethod: null,
    payMoney: null,
    tradeTerms: null,
    bankName: null,
    branchName: null,
    branchCode: null,
    accountNo: null,
    accountNameKana: null,
    salesUserCode: null,
    note: null,
    infoHistory: null,
    infoSalesActivity: null,
    infoOrderFlow: null,
    infoTransactionProgress: null,
    infoCurrentOrders: null,
    infoFutureProposals: null,
    infoCompetitors: null,
    infoRequirements: null,
    infoSalesIdeas: null,
    infoManagementNotes: null,
    infoOther: null,
    createUserId: null,
    createDate: null,
    updateUserId: null,
    updateDate: null,
    drawingMemo: null,
    drawingDate: null,
    billPaymentDay: null,
    billPay: null,
    creditSalesPay: null,
    taxFraction: null,
    taxInFlag: null,
    budgetFlag: null,
    startDate: null,
    endDate: null,
    introducer: null,
    keii: null,
    previousPerson: null,
    salesTrends: null,
    grossProfit: null,
    grossProfitByProduct: null,
    companyContent: null,
    keyPerson: null,
    orderRate: null,
    ippanPub: null,
    textPub: null,
    gyokaiPub: null,
    shoinPub: null,
    tsushinEdu: null,

    otherPub: null,
    businessResult: null,
    companyFeatures: null,
    customerTrend: null,
    whatHappened: null,
    responseToCompetitors: null,
    salesGoal: null,
    externalItems: null,
    internalItems: null,
    quotationPoint: null,
    mainProducts: null,
    totalOrderAmount: null,
    rivalInfo: null,
    customerContactInfo: null,
    orgChart: null,
    pq: null,
    vq: null,
    mq: null,
    mRate: null,
    accidentHistory: null,
    customerVoice: null,
    annualActionPlan: null,
    lostOrders: null,
    growthPotential: null,
    monthlyPlan: null,
    createdAt: new Date().toISOString(),
    ...customerData,
});


export const MOCK_CUSTOMERS: Customer[] = [
  createMockCustomer({
    id: 'cust_demo_01',
    customerName: 'カフェ・ソレイユ',
    customerNameKana: 'カフェソレイユ',
    phoneNumber: '03-1234-5678',
    representative: '山田 花子',
    annualSales: '5000000',
  }),
  createMockCustomer({
    id: 'cust_demo_02',
    customerName: '株式会社TechNext',
    customerNameKana: 'カブシキガイシャテックネクスト',
    phoneNumber: '03-9876-5432',
    representative: '鈴木 一郎',
    annualSales: '120000000',
  }),
  createMockCustomer({
    id: 'cust_demo_03',
    customerName: 'デザインスタジオ・イロドリ',
    customerNameKana: 'デザインスタジオイロドリ',
    phoneNumber: '045-111-2222',
    representative: '高橋 さくら',
    annualSales: '8500000',
  }),
];