import React, { useState } from 'react';
import { RefreshCw } from './Icons';

interface DatabaseSetupInstructionsModalProps {
  onRetry: () => void;
}

const sqlScript = `-- Supabase SQL Editorで以下のスクリプト全体を実行してください。
-- このスクリプトは何度実行しても安全なように設計されています。

-- =================================================================
-- === 最重要: RLS再帰エラーの修正 ===
-- =================================================================
-- usersテーブルに設定されている可能性のある、無限再帰を引き起こすRLSポリシーを無効化します。
-- これを最初に実行することが、すべての問題を解決する鍵となります。
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;


-- 1. 既存テーブルの作成 (存在しない場合のみ)

-- 部署と役職テーブル (usersテーブルが依存)
CREATE TABLE IF NOT EXISTS public.departments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.positions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE
);

-- ユーザーマスターテーブル (emailをNULL許容、部署・役職FKを追加)
-- 主キーがauth.usersのidを参照するように修正
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT,
  department_id UUID REFERENCES public.departments(id),
  position_id UUID REFERENCES public.positions(id),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  role TEXT NOT NULL DEFAULT 'user'
);

-- 案件情報を保存する "jobs" テーブル
CREATE TABLE IF NOT EXISTS public.jobs (
  id TEXT PRIMARY KEY,
  client_name TEXT NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  due_date DATE NOT NULL,
  quantity INTEGER NOT NULL,
  paper_type TEXT NOT NULL,
  finishing TEXT NOT NULL,
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  price INTEGER NOT NULL,
  variable_cost INTEGER NOT NULL,
  invoice_status TEXT NOT NULL,
  invoiced_at TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  ready_to_invoice BOOLEAN,
  invoice_id TEXT
);

-- 会計の仕訳情報を保存する "journal_entries" テーブル
CREATE TABLE IF NOT EXISTS public.journal_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  account TEXT NOT NULL,
  debit INTEGER NOT NULL DEFAULT 0,
  credit INTEGER NOT NULL DEFAULT 0,
  description TEXT
);

-- 勘定科目マスターテーブル
CREATE TABLE IF NOT EXISTS public.account_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category_code TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- 顧客情報を保存する "customers" テーブル
CREATE TABLE IF NOT EXISTS public.customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_code VARCHAR,
    customer_name VARCHAR NOT NULL,
    customer_name_kana VARCHAR,
    representative VARCHAR,
    phone_number VARCHAR,
    address_1 VARCHAR,
    company_content TEXT,
    annual_sales VARCHAR,
    employees_count VARCHAR,
    note TEXT,
    info_sales_activity TEXT,
    info_requirements TEXT,
    info_history TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    post_no VARCHAR,
    address_2 VARCHAR,
    fax VARCHAR,
    closing_day TEXT,
    monthly_plan TEXT,
    pay_day TEXT,
    recovery_method TEXT,
    user_id UUID REFERENCES public.users(id)
);

-- 従業員情報を保存する "employees" テーブル
CREATE TABLE IF NOT EXISTS public.employees (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  department TEXT,
  position TEXT,
  hire_date DATE,
  salary INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- リード管理テーブル
CREATE TABLE IF NOT EXISTS public.leads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    company TEXT NOT NULL,
    source TEXT,
    tags TEXT[],
    message TEXT,
    updated_at TIMESTAMPTZ,
    referrer TEXT,
    referrer_url TEXT,
    landing_page_url TEXT,
    search_keywords TEXT,
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    utm_term TEXT,
    utm_content TEXT,
    user_agent TEXT,
    ip_address TEXT,
    device_type TEXT,
    browser_name TEXT,
    os_name TEXT,
    country TEXT,
    city TEXT,
    region TEXT,
    employees TEXT,
    budget TEXT,
    timeline TEXT,
    inquiry_type TEXT,
    inquiry_types TEXT[],
    info_sales_activity TEXT
);

-- 2. 受信トレイ機能用の新規テーブル作成
CREATE TABLE IF NOT EXISTS public.inbox_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  status TEXT NOT NULL,
  extracted_data JSONB,
  error_message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);


-- 3. 承認ワークフロー用のテーブル作成と修正

-- 申請種別マスターテーブル
CREATE TABLE IF NOT EXISTS public.application_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(10) UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 承認ルートマスターテーブル
CREATE TABLE IF NOT EXISTS public.approval_routes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  route_data JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);


-- 全ての申請を格納する中央テーブル
CREATE TABLE IF NOT EXISTS public.applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  applicant_id UUID REFERENCES public.users(id),
  application_code_id UUID REFERENCES public.application_codes(id),
  form_data JSONB,
  status TEXT NOT NULL DEFAULT 'draft',
  submitted_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  rejected_at TIMESTAMPTZ,
  current_level INTEGER,
  approver_id UUID REFERENCES public.users(id),
  rejection_reason TEXT,
  approval_route_id UUID REFERENCES public.approval_routes(id),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);


-- 発注・在庫テーブル
CREATE TABLE IF NOT EXISTS public.purchase_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    supplier_name TEXT NOT NULL,
    item_name TEXT NOT NULL,
    order_date DATE NOT NULL DEFAULT NOW(),
    quantity NUMERIC NOT NULL,
    unit_price NUMERIC NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.inventory_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    unit TEXT NOT NULL,
    unit_price NUMERIC NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. 請求書関連テーブル
CREATE TABLE IF NOT EXISTS public.invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_no TEXT UNIQUE NOT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE,
    customer_name TEXT NOT NULL,
    subtotal_amount NUMERIC NOT NULL,
    tax_amount NUMERIC NOT NULL,
    total_amount NUMERIC NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    paid_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.invoice_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id UUID REFERENCES public.invoices(id) ON DELETE CASCADE,
    job_id TEXT,
    description TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    unit TEXT NOT NULL,
    unit_price NUMERIC NOT NULL,
    line_total NUMERIC NOT NULL,
    sort_index INTEGER NOT NULL
);


-- =================================================================
-- === 重要: ユーザ同期の問題を修正するトリガー関数 ===
-- =================================================================
-- auth.usersに新しいユーザーが追加された際に、public.usersにレコードを同期します。
-- emailが取得できない場合でも、エラーを起こさずプレースホルダー値を挿入するように修正済みです。

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_email text;
  v_name  text;
BEGIN
  -- name: raw_user_meta_dataからfull_nameを取得、なければemail、それもなければ'New User'
  v_name := COALESCE(
    NEW.raw_user_meta_data->>'full_name',
    NEW.email,
    'New User'
  );

  -- email: 複数のソースからemailを探し、なければプレースホルダーを生成
  SELECT COALESCE(
    NEW.email,
    (SELECT i.identity_data->>'email'
     FROM auth.identities i
     WHERE i.user_id = NEW.id
     ORDER BY i.created_at DESC
     LIMIT 1),
    'no-email+' || NEW.id::text || '@example.local'
  )
  INTO v_email;

  -- public.usersテーブルに挿入。既に存在する場合は何もしない
  INSERT INTO public.users (id, name, email, role)
  VALUES (NEW.id, v_name, v_email, 'user')
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
EXCEPTION
  WHEN OTHERS THEN
    -- エラーが発生してもAuthプロセスをブロックしないように、ログを出力して正常に終了
    RAISE NOTICE 'handle_new_user failed for user_id=%: %', NEW.id, SQLERRM;
    RETURN NEW;
END;
$$;

-- auth.usersテーブルに対するトリガーを作成または確認
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =================================================================
-- === 重要: 過去に同期失敗したユーザーを補完する処理 ===
-- =================================================================
-- auth.usersに存在するがpublic.usersに存在しないユーザーを検出し、補完挿入します。
INSERT INTO public.users (id, name, email, role)
SELECT
  au.id,
  COALESCE(au.raw_user_meta_data->>'full_name', au.email, 'New User'),
  COALESCE(
    au.email,
    (SELECT i.identity_data->>'email'
     FROM auth.identities i
     WHERE i.user_id = au.id
     ORDER BY i.created_at DESC
     LIMIT 1),
    'no-email+' || au.id::text || '@example.local'
  ),
  'user'
FROM auth.users au
LEFT JOIN public.users pu ON pu.id = au.id
WHERE pu.id IS NULL;


-- 5. アプリケーションの動作に必要な初期データの登録
-- 勘定科目マスターの初期データ
INSERT INTO public.account_items (code, name, category_code, sort_order, is_active) VALUES
  ('1111', '現金', 'NOC', 0, true),
  ('1121', '売掛金', 'NOC', 0, true),
  ('2111', '買掛金', 'NOC', 0, true),
  ('2112', '未払金', 'NOC', 0, true),
  ('4111', '売上', 'NOC', 4, true),
  ('5111', '仕入', 'NOC', 5, true),
  ('5121', '経費', 'NOC', 5, true),
  ('5122', '旅費交通費', 'TRP', 5, true)
ON CONFLICT (code) DO NOTHING;

-- 申請種別マスターの初期データ
INSERT INTO public.application_codes (code, name, description) VALUES
  ('EXP', '経費精算申請', '出張費や備品購入費などの経費を精算するための申請です。'),
  ('TRP', '交通費申請', '業務上の移動にかかった交通費を申請します。'),
  ('LEV', '休暇申請', '有給休暇や欠勤などの休暇を申請します。'),
  ('APL', '稟議申請', '金額の発生しない承認（契約締結など）を申請します。'),
  ('DLY', '日報', '日々の業務内容を報告します。'),
  ('WKR', '週報', '週間の業務内容と成果を報告します。')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;


-- アプリケーションの基本動作に必要なデモユーザーを登録します
INSERT INTO public.users (id, name, email, role)
SELECT * FROM (VALUES
  ('a1b2c3d4-e5f6-4890-8234-567890abcdef'::uuid, '山田 太郎 (部長)', 'yamada.taro@example.com', 'admin'),
  ('b2c3d4e5-f6a7-4901-8345-67890abcdef1'::uuid, '鈴木 花子 (課長)', 'suzuki.hanako@example.com', 'user'),
  ('c3d4e5f6-a7b8-4012-8456-7890abcdef12'::uuid, '橋本 唱一', 'hashimoto.shoichi@example.com', 'user')
) AS v(id, name, email, role)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, email = EXCLUDED.email;

-- 従業員データの初期登録
INSERT INTO public.employees (id, name, department, position, hire_date, salary) VALUES
('e1e1e1e1-e1e1-41e1-81e1-e1e1e1e1e1e1'::uuid, '佐藤 一郎', '営業部', '部長', '2010-04-01', 500000),
('e2e2e2e2-e2e2-42e2-82e2-e2e2e2e2e2e2'::uuid, '田中 次郎', '製造部', '課長', '2015-04-01', 400000),
('e3e3e3e3-e3e3-43e3-83e3-e3e3e3e3e3e3'::uuid, '伊藤 三郎', '営業部', '担当', '2020-04-01', 300000)
ON CONFLICT (id) DO NOTHING;


-- 6. RLS (Row-Level Security) の有効化とポリシー設定
-- 注意: これは開発用の基本的なポリシーです。認証済みユーザーはほぼ全ての操作が可能です。
-- 本番環境では、要件に応じてより厳密なポリシーを定義してください。

DO $$
DECLARE
    t_name TEXT;
    -- usersテーブルはRLSを無効化したままなので、ループ対象から除外します。
    tables TEXT[] := ARRAY[
        'jobs', 'journal_entries', 'account_items', 'customers', 'employees', 'leads', 
        'inbox_items', 'application_codes', 'approval_routes', 'applications', 
        'purchase_orders', 'inventory_items', 'invoices', 'invoice_items',
        'departments', 'positions'
    ];
BEGIN
    -- usersテーブルのRLSが無効化されていることを確認
    RAISE NOTICE 'RLS for public.users remains disabled to prevent recursion.';

    FOREACH t_name IN ARRAY tables
    LOOP
        -- テーブルでRLSを有効化
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t_name);
        
        -- 既存のポリシーを削除して再作成
        EXECUTE format('DROP POLICY IF EXISTS "Allow all access for authenticated users" ON public.%I;', t_name);
        
        -- ポリシー: 認証済みユーザーは全操作が可能
        EXECUTE format('
            CREATE POLICY "Allow all access for authenticated users"
            ON public.%I
            FOR ALL
            TO authenticated
            USING (true)
            WITH CHECK (true);
        ', t_name);
        RAISE NOTICE 'RLS policy applied to public.%', t_name;
    END LOOP;
END;
$$;
`;

const DatabaseSetupInstructionsModal: React.FC<DatabaseSetupInstructionsModalProps> = ({ onRetry }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlScript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 bg-slate-100 dark:bg-slate-900 flex justify-center items-center z-[200] p-4 font-sans">
      <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-2xl w-full max-w-4xl h-[90vh] flex flex-col">
        <div className="p-6 border-b border-slate-200 dark:border-slate-700">
          <h2 className="text-2xl font-bold text-slate-800 dark:text-white">データベース セットアップガイド</h2>
          <p className="mt-1 text-slate-500 dark:text-slate-400">
            以下のSQLスクリプトをSupabaseのSQL Editorにコピー＆ペーストして実行し、必要なテーブルと設定をセットアップしてください。
          </p>
        </div>
        <div className="flex-1 p-6 overflow-y-auto bg-slate-50 dark:bg-slate-900/50">
          <pre className="text-xs p-4 bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 whitespace-pre-wrap break-all">
            <code>{sqlScript}</code>
          </pre>
        </div>
        <div className="flex justify-between items-center p-4 bg-slate-100 dark:bg-slate-800/50 border-t border-slate-200 dark:border-slate-700">
          <button
            onClick={handleCopy}
            className={`font-semibold py-2 px-4 rounded-lg ${
              copied ? 'bg-green-600 text-white' : 'bg-blue-600 text-white hover:bg-blue-700'
            }`}
          >
            {copied ? 'コピーしました！' : 'スクリプトをコピー'}
          </button>
          <button
            onClick={onRetry}
            className="flex items-center gap-2 bg-white dark:bg-slate-700 text-slate-700 dark:text-slate-200 font-semibold py-2 px-4 rounded-lg border border-slate-300 dark:border-slate-600 hover:bg-slate-100 dark:hover:bg-slate-600"
          >
            <RefreshCw className="w-5 h-5" />
            セットアップ後に再接続
          </button>
        </div>
      </div>
    </div>
  );
};

export default DatabaseSetupInstructionsModal;